### ISSUE TITLE
[FR] Support SQLite3

### ISSUE THREAD

**Issue by emisjerry** [hymkor/sqlbless#1]
Hi,

Is tere any way to support SQLite3?
Thanks.

Jerry

**Comment by hymkor** [comment]
Thank you.

I was hesitant because it would be difficult to implement if there were a large number of databases to support, but if there is a request, I would like to work for SQLite3 after the current modifications are completed. (since v0.12)

**Comment by emisjerry** [comment]
Thank you for your willingness to add this feature!

BTW, i've recorded a YouTube video for your works: 

- Nyagos: https://youtu.be/WsfIrBWwAh0
- SQL-Bless and CSVI: https://youtu.be/_cxBQKpfUds

Although they are all introduced in Chinese, they are accompanied by CC subtitles in English, Japanese, etc. Maybe you'll be interested.

**Comment by hymkor** [comment]
Thank you. I saw them yesterday and they are very encouraging!

I would create links to them from README.md of the repositories .

**Comment by hymkor** [comment]
SQLite3 is supported now on [Release v0.12.0 · hymkor/sqlbless](https://github.com/hymkor/sqlbless/releases/tag/v0.12.0) !

**Comment by emisjerry** [comment]
👍
